# Generated by Django 4.2 on 2024-08-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('submission_year', models.PositiveIntegerField(default=2024)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_phone', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('article_pdf', models.FileField(blank=True, null=True, upload_to='article_pdf/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default=('submitted', 'Submitted'), max_length=20)),
                ('submited_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
