# Generated by Django 4.2 on 2024-08-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_article_copyright_article_article_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='submited_date',
            field=models.DateTimeField(),
        ),
    ]
