# Generated by Django 4.2 on 2024-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='submited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
