# Generated by Django 4.2 on 2024-08-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_issues_article_co_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='submited_by',
            new_name='submitted_by',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='submited_date',
            new_name='submitted_date',
        ),
    ]
