# Generated by Django 4.2 on 2024-09-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_issue_delete_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
